#create database project3 default character set utf8 collate utf8_general_ci;

use project3;
/*
CREATE TABLE MEMBER (
mno				INT			PRIMARY KEY AUTO_INCREMENT,
id				VARCHAR(50)	NOT NULL UNIQUE,
pwd				VARCHAR(100)	NOT NULL,
mname			VARCHAR(50)	NOT NULL,
nickname		VARCHAR(50)	NOT NULL UNIQUE,
is_admin		BOOLEAN		NOT NULL default false,
birth_date		DATE		NOT NULL,
email			VARCHAR(50)	NOT NULL,
phone			VARCHAR(20)	NOT NULL,
address			VARCHAR(50)	NOT NULL,
reg_date		DATETIME	DEFAULT	 CURRENT_TIMESTAMP,
account			VARCHAR(50)	NOT NULL UNIQUE,
deposit			BIGINT		NOT NULL
)
*/

/*
CREATE TABLE CORPORATION (
	Cno					CHAR(6)		PRIMARY KEY,
	Cname				VARCHAR(50)	NOT NULL,
	Overview			VARCHAR(300),
	Shares_outstanding	BIGINT		NOT NULL,
	Sector				VARCHAR(30)	
)
*/

/*
CREATE TABLE BOARD (
Bno			INT				PRIMARY KEY AUTO_INCREMENT,
Title		VARCHAR(100)	NOT NULL,
Content		TEXT			NOT NULL,
Write_date	DATETIME		DEFAULT CURRENT_TIMESTAMP,
Hit			BIGINT			NOT NULL DEFAULT 0,
Fav			BIGINT			NOT NULL DEFAULT 0,
Mno			INT				NOT NULL,
Cno			CHAR(6),
FOREIGN KEY(Mno)	REFERENCES	MEMBER(Mno) ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY(Cno)	REFERENCES	CORPORATION(Cno) ON UPDATE CASCADE ON DELETE SET NULL
)
*/
/*
CREATE TABLE HOLDERS (
	Hno			INT				PRIMARY KEY AUTO_INCREMENT,
	Cno			CHAR(6)			NOT NULL,
	Info		VARCHAR(50)		NOT NULL,
	Amount		BIGINT			NOT NULL,
	Ratio		DECIMAL(4, 2)	NOT NULL,
	FOREIGN KEY	(Cno)	REFERENCES	CORPORATION(Cno) ON UPDATE CASCADE ON DELETE CASCADE
)
*/

/*
CREATE TABLE PRICE (
	Cno				CHAR(6)	,
	Date			DATE		,
	Open			INT			,
	Close			INT			,
	High			INT			,
	Low				INT			,
	Volume			BIGINT		,
	Change_rate		DOUBLE		,
	FOREIGN KEY(Cno)	REFERENCES	CORPORATION(Cno),
	PRIMARY KEY(Cno, Date)
)
*/

/*
	must import price data first
*/
#update price set date = date_add(date, interval 120 day) order by cno, date desc;

/*
CREATE TABLE ORDERS (
	Ono			INT			PRIMARY KEY AUTO_INCREMENT,
	Mno			INT			,
	Cno			CHAR(6)		,
	Order_time	DATETIME	NOT NULL DEFAULT CURRENT_TIMESTAMP,
	Trade_time	DATETIME	DEFAULT NULL,
	Is_sale		BOOLEAN		NOT NULL,	# SALE, BUY
	State		VARCHAR(10)	NOT NULL	DEFAULT 'WAIT',	# WAIT, COMPLETE, CANCEL
	Quantity	BIGINT		NOT NULL,
	Gain		DOUBLE		,
	Price		INT			NOT NULL, # double -> int
	FOREIGN KEY(Mno)	REFERENCES	MEMBER(Mno) ON DELETE SET NULL,
	FOREIGN KEY(Cno)	REFERENCES	CORPORATION(Cno) ON DELETE SET NULL
)
*/
/*
CREATE TABLE POSSESSES (
	Mno			INT			NOT NULL,
	Cno			VARCHAR(6)	NOT NULL,
	Quantity	BIGINT		NOT NULL,
	Avg_price	DOUBLE		NOT NULL,
	FOREIGN KEY(Mno)	REFERENCES	MEMBER(Mno) ON DELETE CASCADE,
	FOREIGN KEY(Cno)	REFERENCES	CORPORATION(Cno) ON DELETE CASCADE,
    PRIMARY KEY(Mno, Cno)
)
*/

/*
CREATE TABLE INTEREST_GROUP (
	Mno			INT	,
	Gname		VARCHAR(50)	,
	FOREIGN KEY(Mno)	REFERENCES MEMBER(Mno) ON DELETE CASCADE,
	PRIMARY KEY(Mno, Gname)
);

CREATE TABLE INTERESTS (
	Mno			INT,
	Gname		VARCHAR(50),
	Cno			CHAR(6),
	FOREIGN KEY(Mno, Gname)	REFERENCES INTEREST_GROUP(Mno, Gname) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(Cno)		REFERENCES CORPORATION(Cno) ON UPDATE CASCADE ON DELETE CASCADE,
	PRIMARY KEY(Mno, Gname, Cno)
);
*/
/*
CREATE TABLE REPLY (
	Rno				INT				PRIMARY KEY AUTO_INCREMENT,
	Content			VARCHAR(300)	NOT NULL,
	Write_date		DATETIME		DEFAULT CURRENT_TIMESTAMP,
	Mno				INT				NOT NULL,
	Bno				INT				NOT NULL,
	FOREIGN KEY(Mno)	REFERENCES	MEMBER(Mno) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(Bno)	REFERENCES	BOARD(Bno) ON DELETE CASCADE ON UPDATE CASCADE
);
*/


